# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22f30da03cbd54200a320ad238045a509e0b559f0872167f8916ebcb80167a777c8db26edd7d2f2c208a9ed5b8529d9003e21bb73f3da5ccfe7c545cf5b4588

test:
  secret_key_base: 9719fdf5d2c9328b81168be7e8d50f281731d666d719e2e3328614df79bb885a10569bf3830b5738c26aaf309981a5ae6fff71701e39329d8dd1731f1dfa40ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
